**==MASSCNT.FOR
      SUBROUTINE MASSCNT(DEB)
      IMPLICIT REAL*8(A-H, L, M, O-Z)
      INTEGER MAXMSH
      PARAMETER (MAXMSH = 2000)
      COMMON /CNSTS / CPI, PI4, CLN10, CA, CB, CC, CD, CG, CR(2), CEVB, 
     &                CEN, CPL, CMEVMU, CSECYR, LSUN, MSUN, RSUN, TSUNYR
      COMMON /INF   / AF, AT, VX16, AM, VX1, VQK, AR, L, VX4, VX12,  
     :                VX20, VX14, HORB, HSPIN, VX3, WI(45)
      REAL M
      REAL MASSSH(MAXMSH)
      COMMON /MASTRK/ MASSSH(MAXMSH)
      M = DEXP(AM)
      REAL TENG, SMASS, FMASS
      COMMON /ARTENG/ TENG, SMASS, FMASS
      